name: sellerkitcalllog
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  path_provider: ^2.0.11
  http: ^1.1.0
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.1
  provider: ^6.0.2
  call_log: ^4.0.0
  flutter_callkit_incoming: ^2.0.3
  flutter_contacts: ^1.1.7+1
  firebase_core: ^2.17.0
  firebase_dynamic_links: ^5.4.7
  share_plus: ^7.2.2
  firebase_messaging: ^14.8.0
  url_launcher: ^6.1.5
  lottie: ^2.7.0
  encrypt: ^5.0.1
  sqflite: ^2.2.2
  device_info_plus: ^9.0.2
  geolocator: ^10.1.0
  introduction_screen: ^3.0.2
  flutter_spinkit: ^5.1.0
  dart_ipify: ^1.1.1
  upgrader: ^9.0.0
  package_info_plus: ^4.2.0
  get_ip_address: ^0.0.6
  network_info_plus: ^4.1.0
  easy_pdf_viewer: ^1.0.6
  system_alert_window: ^2.0.0
  phone_state: ^1.0.3
  flutter_background_service: ^5.0.4
  flutter_overlay_window: ^0.4.4
  external_app_launcher: ^4.0.0
  flutter_alarm_background_trigger: ^1.0.2
  flutter_local_notifications: ^17.0.0
  device_calendar: ^4.3.2
  jiffy: ^5.0.0
  pdf: ^3.10.8
  open_file: ^3.3.2
  printing: ^5.12.0
  timeline_tile: ^2.0.0
  google_maps_flutter: ^2.6.1

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/SellerkitCaller.png"

flutter_native_splash:
  
  color: "#42a5f5"
  #background_image: "assets/background.png"

  image: Assets/SellerkitCaller.png

  #branding: assets/dart.png
  #branding_mode: bottom

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png
  android_12:
    image: Assets/SellerkitCaller.png

    # Splash screen background color.
    color: "#42a5f5"

    #icon_background_color: "#111111"
    #branding: assets/dart.png

    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"

  android: true
  ios: true
  #web: false

  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.gif
  #image_dark_web: assets/splash-invert-web.gif
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/dart_dark-ios.png
  #branding_web: assets/brand-web.gif
  #branding_dark_web: assets/dart_dark-web.gif

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom, SystemUiOverlay.top], );
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'



flutter:
  generate: true
  
  uses-material-design: true

  
  assets:
    - Assets/
    
  
  

  
  

  
  
  
  
  
  fonts:
    - family: SEGOEUIL
      fonts:
        - asset: Assets/SEGOEUIL.ttf
    - family: HelveticaNow
      fonts:
        - asset: Assets/HelveticaNow.ttf
    - family: ayar
      fonts:
        - asset: Assets/ayar.ttf
    - family: Celias-Medium
      fonts:
        - asset: Assets/Celias-Medium.ttf
    - family: Ordina-WideThin
      fonts:
        - asset: Assets/Ordina-WideThin.ttf
    - family: TruenoRound
      fonts:
        - asset: Assets/TruenoRound.otf
    - family: Quicksand_Light
      fonts:
        - asset: Assets/Quicksand/Quicksand_Light.otf
    - family: NovaRegular
      fonts:
        - asset: Assets/nova/NovaRegular.otf
    - family: OpenSans-Regular
      fonts:
        - asset: Assets/OpenSans/OpenSans-Regular.ttf
    - family: Sabon
      fonts:
        - asset: Assets/Sabon/Sabon.ttf
    - family: Ingeborg
      fonts:
        - asset: Assets/Ingeborg-Regular.ttf
    - family: Calibri
      fonts:
        - asset: Assets/Calibri.ttf
    - family: CALIBRIB
      fonts:
        - asset: Assets/CALIBRIB.TTF
    - family: CalibriBold
      fonts:
        - asset: Assets/CalibriBold.ttf
  
  
  
